/* Generated by scripts/refresh-market-refs.ts — edit the script, then `npm run refresh:market`. */

/**
 * Dated external price references. Shown beside the self-hosted TCO as a
 * sanity bound; never used to score any index.
 */
export const OPENROUTER_LLAMA31_8B = {
  model: 'Llama-3.1-8B',
  slug: 'meta-llama/llama-3.1-8b-instruct',
  usdPerMTokIn: 0.05,
  usdPerMTokOut: 0.08,
  asOf: '2026-09-13',
  scope: 'OpenRouter listed input/output price; the output price is what self-hosted output cost is compared with',
  source: 'OpenRouter listed price, Meta Llama 3.1 8B Instruct',
  href: 'https://openrouter.ai/meta-llama/llama-3.1-8b-instruct',
} as const;

/** How many times the self-hosted cost floor exceeds the API list price. */
export function selfHostedToApiRatio(selfHostedUsd: number, apiUsd: number): number | null {
  if (!(selfHostedUsd > 0) || !(apiUsd > 0)) return null;
  return selfHostedUsd / apiUsd;
}
