/* Generated by scripts/build-efficiency-index.ts — do not edit by hand. */
import type { DomainScales, IndexRow } from './score';

export interface EfficiencySnapshot {
  version: string;
  generatedAt: string;
  source: string;
  sourceModified: string;
  n: number;
  verified: number;
  estimated: number;
  scales: DomainScales;
  rows: IndexRow[];
}

export const EFFICIENCY_SNAPSHOT: EfficiencySnapshot = {
  "version": "1.1",
  "generatedAt": "2026-09-07",
  "source": "json/current/data.synthetic_distributional.json",
  "sourceModified": "2026-08-30",
  "n": 101,
  "verified": 101,
  "estimated": 0,
  "scales": {
    "chat": {
      "min": 0.03094570137744231,
      "max": 1.7235984375142104
    },
    "coding": {
      "min": 0.010228947625713183,
      "max": 0.684986521183474
    },
    "terminal": {
      "min": 0.007829023155155167,
      "max": 0.7670495525684725
    },
    "computerUse": {
      "min": 0.022736923640110568,
      "max": 0.9430401499153881
    },
    "cost": {
      "min": 22355.773486982725,
      "max": 8582549.192720909
    }
  },
  "rows": [
    {
      "id": "Llama-3.1-8B|H100x4|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 99.2,
      "cost": 50.5,
      "domains": {
        "chat": 100,
        "coding": 96.7,
        "terminal": 100,
        "computerUse": 100
      },
      "raw": {
        "tpotMs": 5.2,
        "ttftMs": 414.7,
        "tokPerSec": 1946.2,
        "usdPerMTok": 2.28,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GBx4|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 97.6,
      "cost": 59.5,
      "domains": {
        "chat": 96.5,
        "coding": 98.5,
        "terminal": 96.1,
        "computerUse": 99.3
      },
      "raw": {
        "tpotMs": 7.2,
        "ttftMs": 263.1,
        "tokPerSec": 1660.3,
        "usdPerMTok": 1.33,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100x2|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 97,
      "cost": 58.6,
      "domains": {
        "chat": 93.4,
        "coding": 99.9,
        "terminal": 96.3,
        "computerUse": 98.2
      },
      "raw": {
        "tpotMs": 6.1,
        "ttftMs": 311.2,
        "tokPerSec": 1579,
        "usdPerMTok": 1.4,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|H100x4|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 96.1,
      "cost": 45.8,
      "domains": {
        "chat": 92.3,
        "coding": 100,
        "terminal": 96.1,
        "computerUse": 96.2
      },
      "raw": {
        "tpotMs": 7.8,
        "ttftMs": 269.5,
        "tokPerSec": 1465.1,
        "usdPerMTok": 3.03,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 95,
      "cost": 68.5,
      "domains": {
        "chat": 91,
        "coding": 99,
        "terminal": 95,
        "computerUse": 95
      },
      "raw": {
        "tpotMs": 6.8,
        "ttftMs": 365,
        "tokPerSec": 1435.9,
        "usdPerMTok": 0.77,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100x4|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 94.2,
      "cost": 49.6,
      "domains": {
        "chat": 93.5,
        "coding": 98.8,
        "terminal": 93.8,
        "computerUse": 90.6
      },
      "raw": {
        "tpotMs": 5,
        "ttftMs": 405.1,
        "tokPerSec": 1836.7,
        "usdPerMTok": 2.41,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 93.3,
      "cost": 68.2,
      "domains": {
        "chat": 85.6,
        "coding": 97.6,
        "terminal": 96.1,
        "computerUse": 93.8
      },
      "raw": {
        "tpotMs": 7.4,
        "ttftMs": 425.6,
        "tokPerSec": 1404.2,
        "usdPerMTok": 0.79,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100x4|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 93.3,
      "cost": 49.1,
      "domains": {
        "chat": 98,
        "coding": 87.1,
        "terminal": 91.6,
        "computerUse": 96.3
      },
      "raw": {
        "tpotMs": 6.1,
        "ttftMs": 544.7,
        "tokPerSec": 1780.5,
        "usdPerMTok": 2.49,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GBx2|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 93.1,
      "cost": 67,
      "domains": {
        "chat": 91.7,
        "coding": 95.7,
        "terminal": 91.4,
        "computerUse": 93.4
      },
      "raw": {
        "tpotMs": 10.7,
        "ttftMs": 273.1,
        "tokPerSec": 1307.8,
        "usdPerMTok": 0.85,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100x4|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 92.9,
      "cost": 49.6,
      "domains": {
        "chat": 92.8,
        "coding": 91.7,
        "terminal": 90.7,
        "computerUse": 96.5
      },
      "raw": {
        "tpotMs": 7.6,
        "ttftMs": 396.5,
        "tokPerSec": 1836.7,
        "usdPerMTok": 2.41,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|H100x2|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 92.5,
      "cost": 53.8,
      "domains": {
        "chat": 88.7,
        "coding": 95.7,
        "terminal": 93.3,
        "computerUse": 92.3
      },
      "raw": {
        "tpotMs": 10.2,
        "ttftMs": 279.5,
        "tokPerSec": 1184.7,
        "usdPerMTok": 1.87,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100x2|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 92.4,
      "cost": 59.2,
      "domains": {
        "chat": 91.4,
        "coding": 96.7,
        "terminal": 93.4,
        "computerUse": 88.1
      },
      "raw": {
        "tpotMs": 5.9,
        "ttftMs": 406.7,
        "tokPerSec": 1641.5,
        "usdPerMTok": 1.35,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|H100x4|vllm|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 92.4,
      "cost": 40.8,
      "domains": {
        "chat": 88.2,
        "coding": 95.6,
        "terminal": 93.8,
        "computerUse": 92
      },
      "raw": {
        "tpotMs": 10.5,
        "ttftMs": 325.5,
        "tokPerSec": 1084.7,
        "usdPerMTok": 4.09,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100x2|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 91.4,
      "cost": 58.3,
      "domains": {
        "chat": 96.4,
        "coding": 82.9,
        "terminal": 93.1,
        "computerUse": 93.1
      },
      "raw": {
        "tpotMs": 7.7,
        "ttftMs": 416.6,
        "tokPerSec": 1556.3,
        "usdPerMTok": 1.42,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|H100x2|sglang|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 91.3,
      "cost": 53.9,
      "domains": {
        "chat": 83.2,
        "coding": 96.5,
        "terminal": 95.9,
        "computerUse": 89.7
      },
      "raw": {
        "tpotMs": 9.8,
        "ttftMs": 326.9,
        "tokPerSec": 1188.4,
        "usdPerMTok": 1.87,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100x2|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 89.4,
      "cost": 57.8,
      "domains": {
        "chat": 89.3,
        "coding": 87.6,
        "terminal": 88.7,
        "computerUse": 92.1
      },
      "raw": {
        "tpotMs": 8.9,
        "ttftMs": 423.1,
        "tokPerSec": 1507.6,
        "usdPerMTok": 1.47,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-120b|A100-40GBx4|vllm|BF16",
      "model": "gpt-oss-120b",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 89.3,
      "cost": 52.8,
      "domains": {
        "chat": 86.5,
        "coding": 91,
        "terminal": 89.3,
        "computerUse": 90.2
      },
      "raw": {
        "tpotMs": 12.7,
        "ttftMs": 294,
        "tokPerSec": 1108.8,
        "usdPerMTok": 1.99,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|A100-40GBx4|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 87.3,
      "cost": 50.6,
      "domains": {
        "chat": 84.3,
        "coding": 90.1,
        "terminal": 88.5,
        "computerUse": 86.4
      },
      "raw": {
        "tpotMs": 13.8,
        "ttftMs": 320.7,
        "tokPerSec": 975.8,
        "usdPerMTok": 2.27,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|H100x4|sglang|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 87.2,
      "cost": 41.8,
      "domains": {
        "chat": 86.6,
        "coding": 90.4,
        "terminal": 90.9,
        "computerUse": 81
      },
      "raw": {
        "tpotMs": 10,
        "ttftMs": 511.5,
        "tokPerSec": 1153.6,
        "usdPerMTok": 3.84,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100x2|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 86.6,
      "cost": 57.9,
      "domains": {
        "chat": 94.4,
        "coding": 75.2,
        "terminal": 86.5,
        "computerUse": 90.2
      },
      "raw": {
        "tpotMs": 8.4,
        "ttftMs": 532.6,
        "tokPerSec": 1514.1,
        "usdPerMTok": 1.46,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|H100x4|sglang|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 86,
      "cost": 36.6,
      "domains": {
        "chat": 76.7,
        "coding": 93.3,
        "terminal": 89.4,
        "computerUse": 84.7
      },
      "raw": {
        "tpotMs": 14.4,
        "ttftMs": 422.4,
        "tokPerSec": 842.1,
        "usdPerMTok": 5.26,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GBx4|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 85,
      "cost": 55.1,
      "domains": {
        "chat": 91.1,
        "coding": 75.6,
        "terminal": 84.5,
        "computerUse": 88.7
      },
      "raw": {
        "tpotMs": 11.6,
        "ttftMs": 427.8,
        "tokPerSec": 1276,
        "usdPerMTok": 1.73,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GBx4|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 83.6,
      "cost": 54.4,
      "domains": {
        "chat": 84.7,
        "coding": 80.2,
        "terminal": 82.7,
        "computerUse": 86.7
      },
      "raw": {
        "tpotMs": 11.4,
        "ttftMs": 534.5,
        "tokPerSec": 1224.2,
        "usdPerMTok": 1.81,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|H100x2|vllm|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 81.7,
      "cost": 45.4,
      "domains": {
        "chat": 80.2,
        "coding": 83.8,
        "terminal": 83.3,
        "computerUse": 79.6
      },
      "raw": {
        "tpotMs": 18.1,
        "ttftMs": 373.8,
        "tokPerSec": 713.7,
        "usdPerMTok": 3.11,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 81.5,
      "cost": 65.3,
      "domains": {
        "chat": 90.9,
        "coding": 70.7,
        "terminal": 81.2,
        "computerUse": 83.3
      },
      "raw": {
        "tpotMs": 12.3,
        "ttftMs": 424.2,
        "tokPerSec": 1183,
        "usdPerMTok": 0.94,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|H100x2|sglang|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 80.4,
      "cost": 45.1,
      "domains": {
        "chat": 78.6,
        "coding": 82.8,
        "terminal": 83.4,
        "computerUse": 76.9
      },
      "raw": {
        "tpotMs": 18.2,
        "ttftMs": 445,
        "tokPerSec": 701.7,
        "usdPerMTok": 3.16,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 79.4,
      "cost": 64.1,
      "domains": {
        "chat": 87.6,
        "coding": 69.7,
        "terminal": 79.2,
        "computerUse": 81.1
      },
      "raw": {
        "tpotMs": 11.8,
        "ttftMs": 534.3,
        "tokPerSec": 1100.9,
        "usdPerMTok": 1.01,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|A100-40GBx4|sglang|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 78.3,
      "cost": 46.6,
      "domains": {
        "chat": 76.5,
        "coding": 79.7,
        "terminal": 81.4,
        "computerUse": 75.6
      },
      "raw": {
        "tpotMs": 14.2,
        "ttftMs": 727.6,
        "tokPerSec": 766.8,
        "usdPerMTok": 2.88,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 77.9,
      "cost": 64,
      "domains": {
        "chat": 80.1,
        "coding": 70.1,
        "terminal": 77.1,
        "computerUse": 84.4
      },
      "raw": {
        "tpotMs": 13.5,
        "ttftMs": 584.4,
        "tokPerSec": 1094.3,
        "usdPerMTok": 1.01,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-27B|H100x4|vllm|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 77.5,
      "cost": 38.6,
      "domains": {
        "chat": 77.6,
        "coding": 74.5,
        "terminal": 77.7,
        "computerUse": 80.1
      },
      "raw": {
        "tpotMs": 16.6,
        "ttftMs": 585.6,
        "tokPerSec": 951.3,
        "usdPerMTok": 4.66,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|3090x4|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 75.3,
      "cost": 80.4,
      "domains": {
        "chat": 74.6,
        "coding": 77.2,
        "terminal": 75.2,
        "computerUse": 74.3
      },
      "raw": {
        "tpotMs": 26.4,
        "ttftMs": 612.7,
        "tokPerSec": 646.4,
        "usdPerMTok": 0.38,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GB|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 73.6,
      "cost": 72.5,
      "domains": {
        "chat": 82.5,
        "coding": 62.7,
        "terminal": 73.8,
        "computerUse": 75.2
      },
      "raw": {
        "tpotMs": 22.2,
        "ttftMs": 586.2,
        "tokPerSec": 908.1,
        "usdPerMTok": 0.61,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GBx2|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 73,
      "cost": 60.5,
      "domains": {
        "chat": 84.3,
        "coding": 60.8,
        "terminal": 74.6,
        "computerUse": 72.2
      },
      "raw": {
        "tpotMs": 20.4,
        "ttftMs": 485.2,
        "tokPerSec": 884.4,
        "usdPerMTok": 1.25,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|3090x2|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 71.8,
      "cost": 91.8,
      "domains": {
        "chat": 74,
        "coding": 73.9,
        "terminal": 71.3,
        "computerUse": 68
      },
      "raw": {
        "tpotMs": 25.6,
        "ttftMs": 610,
        "tokPerSec": 639.7,
        "usdPerMTok": 0.19,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GBx4|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 70.6,
      "cost": 46.8,
      "domains": {
        "chat": 82.2,
        "coding": 67.4,
        "terminal": 60.1,
        "computerUse": 72.7
      },
      "raw": {
        "tpotMs": 27.2,
        "ttftMs": 1372.5,
        "tokPerSec": 775.1,
        "usdPerMTok": 2.85,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 46
      }
    },
    {
      "id": "Qwen3.5-9B|H100x4|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 69.6,
      "cost": 39.2,
      "domains": {
        "chat": 79.4,
        "coding": 63.8,
        "terminal": 64.7,
        "computerUse": 70.5
      },
      "raw": {
        "tpotMs": 26.8,
        "ttftMs": 1068.9,
        "tokPerSec": 984.5,
        "usdPerMTok": 4.5,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|A100-40GBx2|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 69.5,
      "cost": 55.1,
      "domains": {
        "chat": 75.5,
        "coding": 67.6,
        "terminal": 60.7,
        "computerUse": 74.3
      },
      "raw": {
        "tpotMs": 27.2,
        "ttftMs": 534.3,
        "tokPerSec": 638.1,
        "usdPerMTok": 1.73,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|A100-40GBx4|vllm|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 67.7,
      "cost": 41.3,
      "domains": {
        "chat": 76.8,
        "coding": 56.8,
        "terminal": 71.1,
        "computerUse": 66
      },
      "raw": {
        "tpotMs": 30.7,
        "ttftMs": 563.5,
        "tokPerSec": 556.7,
        "usdPerMTok": 3.97,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 67.1,
      "cost": 59.2,
      "domains": {
        "chat": 74,
        "coding": 56.6,
        "terminal": 65.4,
        "computerUse": 72.4
      },
      "raw": {
        "tpotMs": 28.2,
        "ttftMs": 1044.4,
        "tokPerSec": 817,
        "usdPerMTok": 1.36,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GBx2|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 66,
      "cost": 56.2,
      "domains": {
        "chat": 77.2,
        "coding": 56.4,
        "terminal": 64.2,
        "computerUse": 66.2
      },
      "raw": {
        "tpotMs": 38.9,
        "ttftMs": 965.6,
        "tokPerSec": 684,
        "usdPerMTok": 1.62,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 49
      }
    },
    {
      "id": "Llama-3.1-70B|H100x4|vllm|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 65.8,
      "cost": 31.4,
      "domains": {
        "chat": 74.5,
        "coding": 53.4,
        "terminal": 67.1,
        "computerUse": 68.3
      },
      "raw": {
        "tpotMs": 25.4,
        "ttftMs": 600.6,
        "tokPerSec": 616.6,
        "usdPerMTok": 7.19,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.3-70B|H100x4|vllm|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 65.5,
      "cost": 30.5,
      "domains": {
        "chat": 72.4,
        "coding": 54.2,
        "terminal": 67,
        "computerUse": 68.2
      },
      "raw": {
        "tpotMs": 25.5,
        "ttftMs": 592.6,
        "tokPerSec": 583.6,
        "usdPerMTok": 7.6,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-27B|H100x2|vllm|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 65,
      "cost": 44.2,
      "domains": {
        "chat": 70,
        "coding": 58.1,
        "terminal": 62.7,
        "computerUse": 69.2
      },
      "raw": {
        "tpotMs": 24.5,
        "ttftMs": 919.1,
        "tokPerSec": 666,
        "usdPerMTok": 3.33,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen2.5-72B|H100x4|vllm|BF16",
      "model": "Qwen2.5-72B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 64.5,
      "cost": 30.8,
      "domains": {
        "chat": 74.3,
        "coding": 51.8,
        "terminal": 65.4,
        "computerUse": 66.6
      },
      "raw": {
        "tpotMs": 26.8,
        "ttftMs": 663.6,
        "tokPerSec": 594,
        "usdPerMTok": 7.46,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GB|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 63.8,
      "cost": 65,
      "domains": {
        "chat": 63.8,
        "coding": 65.6,
        "terminal": 66.9,
        "computerUse": 59
      },
      "raw": {
        "tpotMs": 24.9,
        "ttftMs": 781.7,
        "tokPerSec": 578,
        "usdPerMTok": 0.96,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|3090|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 63.6,
      "cost": 100,
      "domains": {
        "chat": 68.7,
        "coding": 61.4,
        "terminal": 62.1,
        "computerUse": 62.3
      },
      "raw": {
        "tpotMs": 26.6,
        "ttftMs": 1017.9,
        "tokPerSec": 524.5,
        "usdPerMTok": 0.12,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|A100-40GBx2|sglang|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 62,
      "cost": 50.1,
      "domains": {
        "chat": 63.2,
        "coding": 60.6,
        "terminal": 63.4,
        "computerUse": 60.8
      },
      "raw": {
        "tpotMs": 37.6,
        "ttftMs": 849.9,
        "tokPerSec": 473.3,
        "usdPerMTok": 2.34,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GBx2|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 60.2,
      "cost": 59.1,
      "domains": {
        "chat": 78.7,
        "coding": 65.2,
        "terminal": 61.4,
        "computerUse": 35.4
      },
      "raw": {
        "tpotMs": 22.9,
        "ttftMs": 755.2,
        "tokPerSec": 812.7,
        "usdPerMTok": 1.36,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GB|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 59.9,
      "cost": 61.5,
      "domains": {
        "chat": 57.7,
        "coding": 59.5,
        "terminal": 63.9,
        "computerUse": 58.5
      },
      "raw": {
        "tpotMs": 36.3,
        "ttftMs": 921.5,
        "tokPerSec": 469.6,
        "usdPerMTok": 1.18,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-70B|H100x4|sglang|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 58.8,
      "cost": 28,
      "domains": {
        "chat": 67.8,
        "coding": 58.6,
        "terminal": 53.9,
        "computerUse": 54.7
      },
      "raw": {
        "tpotMs": 26.5,
        "ttftMs": 2138.4,
        "tokPerSec": 501.1,
        "usdPerMTok": 8.85,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 43
      }
    },
    {
      "id": "Llama-3.3-70B|H100x4|sglang|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 58.8,
      "cost": 27.6,
      "domains": {
        "chat": 67.6,
        "coding": 58.2,
        "terminal": 55.3,
        "computerUse": 54.1
      },
      "raw": {
        "tpotMs": 27.4,
        "ttftMs": 1956.3,
        "tokPerSec": 490.8,
        "usdPerMTok": 9.03,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 43
      }
    },
    {
      "id": "Qwen2.5-72B|H100x4|sglang|BF16",
      "model": "Qwen2.5-72B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 58.3,
      "cost": 26.7,
      "domains": {
        "chat": 65.9,
        "coding": 58.3,
        "terminal": 54.5,
        "computerUse": 54.3
      },
      "raw": {
        "tpotMs": 27.8,
        "ttftMs": 2051.8,
        "tokPerSec": 464.9,
        "usdPerMTok": 9.54,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 43
      }
    },
    {
      "id": "Mixtral-8x7B|A100-40GBx4|sglang|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 57.6,
      "cost": 38.2,
      "domains": {
        "chat": 68.6,
        "coding": 53.6,
        "terminal": 57.2,
        "computerUse": 51
      },
      "raw": {
        "tpotMs": 28.4,
        "ttftMs": 1517,
        "tokPerSec": 462.2,
        "usdPerMTok": 4.78,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "gpt-oss-120b|A100-40GBx4|sglang|BF16",
      "model": "gpt-oss-120b",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 55.6,
      "cost": 35.8,
      "domains": {
        "chat": 68.9,
        "coding": 50.7,
        "terminal": 56.5,
        "computerUse": 46.1
      },
      "raw": {
        "tpotMs": 33.2,
        "ttftMs": 3047.9,
        "tokPerSec": 401.2,
        "usdPerMTok": 5.51,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Qwen3-30B-A3B|3090x4|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 55.4,
      "cost": 69.8,
      "domains": {
        "chat": 58.6,
        "coding": 55,
        "terminal": 54.5,
        "computerUse": 53.3
      },
      "raw": {
        "tpotMs": 50.3,
        "ttftMs": 1064,
        "tokPerSec": 341.4,
        "usdPerMTok": 0.72,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GB|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 54.7,
      "cost": 63.6,
      "domains": {
        "chat": 73.6,
        "coding": 36.4,
        "terminal": 58.7,
        "computerUse": 50.1
      },
      "raw": {
        "tpotMs": 69.1,
        "ttftMs": 1936.5,
        "tokPerSec": 531.8,
        "usdPerMTok": 1.04,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GB|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 54.4,
      "cost": 62.8,
      "domains": {
        "chat": 71.2,
        "coding": 37.9,
        "terminal": 56.1,
        "computerUse": 52.2
      },
      "raw": {
        "tpotMs": 63,
        "ttftMs": 2428.9,
        "tokPerSec": 507.3,
        "usdPerMTok": 1.09,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|3090x4|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 54.3,
      "cost": 73.6,
      "domains": {
        "chat": 66.5,
        "coding": 41.3,
        "terminal": 55.2,
        "computerUse": 54.1
      },
      "raw": {
        "tpotMs": 51.2,
        "ttftMs": 1252.3,
        "tokPerSec": 429.7,
        "usdPerMTok": 0.57,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 48
      }
    },
    {
      "id": "gpt-oss-120b|3090x4|vllm|BF16",
      "model": "gpt-oss-120b",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 52,
      "cost": 70.5,
      "domains": {
        "chat": 55.7,
        "coding": 52,
        "terminal": 50.7,
        "computerUse": 49.5
      },
      "raw": {
        "tpotMs": 50.9,
        "ttftMs": 1300.5,
        "tokPerSec": 355.4,
        "usdPerMTok": 0.69,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GBx2|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 52,
      "cost": 43.9,
      "domains": {
        "chat": 62.4,
        "coding": 49.6,
        "terminal": 52,
        "computerUse": 44
      },
      "raw": {
        "tpotMs": 53.3,
        "ttftMs": 3491.8,
        "tokPerSec": 325.8,
        "usdPerMTok": 3.39,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "Qwen3.5-27B|H100x2|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 51.2,
      "cost": 35,
      "domains": {
        "chat": 55.7,
        "coding": 47.3,
        "terminal": 49.8,
        "computerUse": 52
      },
      "raw": {
        "tpotMs": 48,
        "ttftMs": 1976.8,
        "tokPerSec": 382.1,
        "usdPerMTok": 5.8,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-27B|H100x4|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 49.4,
      "cost": 16.7,
      "domains": {
        "chat": 51,
        "coding": 45.9,
        "terminal": 48.8,
        "computerUse": 52.1
      },
      "raw": {
        "tpotMs": 62,
        "ttftMs": 2363.7,
        "tokPerSec": 254.9,
        "usdPerMTok": 17.4,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|3090x4|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 48.3,
      "cost": 63.2,
      "domains": {
        "chat": 49.7,
        "coding": 50.3,
        "terminal": 50.1,
        "computerUse": 42.9
      },
      "raw": {
        "tpotMs": 80.4,
        "ttftMs": 1698.4,
        "tokPerSec": 230.4,
        "usdPerMTok": 1.06,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 42
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GBx4|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 48.2,
      "cost": 37.6,
      "domains": {
        "chat": 59.9,
        "coding": 31,
        "terminal": 44.2,
        "computerUse": 57.6
      },
      "raw": {
        "tpotMs": 100.3,
        "ttftMs": 3065,
        "tokPerSec": 447.2,
        "usdPerMTok": 4.94,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 53
      }
    },
    {
      "id": "Qwen2.5-72B|H100x2|sglang|BF16",
      "model": "Qwen2.5-72B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 47.8,
      "cost": 30.5,
      "domains": {
        "chat": 44.9,
        "coding": 69.3,
        "terminal": 29.1,
        "computerUse": null
      },
      "raw": {
        "tpotMs": 115.7,
        "ttftMs": 2478.7,
        "tokPerSec": 292.2,
        "usdPerMTok": 7.59,
        "loadsUsed": [
          1,
          40,
          80,
          160
        ],
        "domainCount": 3,
        "runCount": 27
      }
    },
    {
      "id": "Qwen3.5-9B|3090x4|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 47.2,
      "cost": 67.5,
      "domains": {
        "chat": 55.6,
        "coding": 49,
        "terminal": 50,
        "computerUse": 34.1
      },
      "raw": {
        "tpotMs": 80.3,
        "ttftMs": 2645.7,
        "tokPerSec": 297.4,
        "usdPerMTok": 0.82,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100x2|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 46.9,
      "cost": 6.5,
      "domains": {
        "chat": 49.3,
        "coding": 42.5,
        "terminal": 49.4,
        "computerUse": 46.6
      },
      "raw": {
        "tpotMs": 54,
        "ttftMs": 915,
        "tokPerSec": 68.8,
        "usdPerMTok": 32.21,
        "loadsUsed": [
          1,
          5,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "gpt-oss-20b|3090x2|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 46.7,
      "cost": 69.2,
      "domains": {
        "chat": 41.8,
        "coding": 51.5,
        "terminal": 54.2,
        "computerUse": 39.2
      },
      "raw": {
        "tpotMs": 128,
        "ttftMs": 1597.1,
        "tokPerSec": 165.2,
        "usdPerMTok": 0.74,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "gpt-oss-20b|3090x4|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 44.6,
      "cost": 63.2,
      "domains": {
        "chat": 52.8,
        "coding": 45.1,
        "terminal": 47,
        "computerUse": 33.6
      },
      "raw": {
        "tpotMs": 90.8,
        "ttftMs": 1291,
        "tokPerSec": 229.6,
        "usdPerMTok": 1.06,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Qwen3.5-9B|2080Tix4|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "2080Tix4",
      "hardwareFamily": "2080 Ti",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 44.4,
      "cost": 79.7,
      "domains": {
        "chat": 47.9,
        "coding": 45.9,
        "terminal": 40,
        "computerUse": 43.8
      },
      "raw": {
        "tpotMs": 107.7,
        "ttftMs": 3408.7,
        "tokPerSec": 281.1,
        "usdPerMTok": 0.4,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 41
      }
    },
    {
      "id": "Qwen3.5-27B|H100|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 44.1,
      "cost": 40.1,
      "domains": {
        "chat": 39.4,
        "coding": 43.8,
        "terminal": 46.8,
        "computerUse": 46.4
      },
      "raw": {
        "tpotMs": 63.4,
        "ttftMs": 4129.6,
        "tokPerSec": 259.1,
        "usdPerMTok": 4.28,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 53
      }
    },
    {
      "id": "gpt-oss-20b|3090|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 41.8,
      "cost": 82.6,
      "domains": {
        "chat": 43.9,
        "coding": 41.4,
        "terminal": 43.4,
        "computerUse": 38.6
      },
      "raw": {
        "tpotMs": 117.2,
        "ttftMs": 1815.1,
        "tokPerSec": 184,
        "usdPerMTok": 0.33,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "Llama-3.1-8B|3090x2|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 40.7,
      "cost": 80.4,
      "domains": {
        "chat": 61.5,
        "coding": 18.2,
        "terminal": 43,
        "computerUse": 40.2
      },
      "raw": {
        "tpotMs": 146.5,
        "ttftMs": 5998,
        "tokPerSec": 322.6,
        "usdPerMTok": 0.38,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "Qwen3.5-27B|H100|vllm|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 39.7,
      "cost": 43.4,
      "domains": {
        "chat": 50.8,
        "coding": 28.1,
        "terminal": 41.6,
        "computerUse": 38.1
      },
      "raw": {
        "tpotMs": 121.2,
        "ttftMs": 5015.1,
        "tokPerSec": 317.5,
        "usdPerMTok": 3.49,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GB|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 39.5,
      "cost": 52.2,
      "domains": {
        "chat": 56.1,
        "coding": 38.3,
        "terminal": 34.4,
        "computerUse": 29
      },
      "raw": {
        "tpotMs": 67.9,
        "ttftMs": 5604.2,
        "tokPerSec": 268.1,
        "usdPerMTok": 2.06,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 40
      }
    },
    {
      "id": "Llama-3.3-70B|A100-40GBx4|vllm|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 38,
      "cost": 21.6,
      "domains": {
        "chat": 38,
        "coding": 37.5,
        "terminal": 41.5,
        "computerUse": 35.1
      },
      "raw": {
        "tpotMs": 59.7,
        "ttftMs": 5922.6,
        "tokPerSec": 170.4,
        "usdPerMTok": 12.97,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|3090x2|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 38,
      "cost": 79.4,
      "domains": {
        "chat": 53.1,
        "coding": 20.9,
        "terminal": 41.4,
        "computerUse": 36.5
      },
      "raw": {
        "tpotMs": 129.1,
        "ttftMs": 4647,
        "tokPerSec": 304.9,
        "usdPerMTok": 0.4,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 48
      }
    },
    {
      "id": "Llama-3.1-70B|A100-40GBx4|vllm|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 37.9,
      "cost": 21.5,
      "domains": {
        "chat": 39.2,
        "coding": 37,
        "terminal": 40.7,
        "computerUse": 34.7
      },
      "raw": {
        "tpotMs": 62.8,
        "ttftMs": 5734.5,
        "tokPerSec": 169.5,
        "usdPerMTok": 13.04,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-120b|3090x4|sglang|BF16",
      "model": "gpt-oss-120b",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 37.1,
      "cost": 58,
      "domains": {
        "chat": 38,
        "coding": 37.8,
        "terminal": 40.1,
        "computerUse": 32.6
      },
      "raw": {
        "tpotMs": 90.5,
        "ttftMs": 2095,
        "tokPerSec": 167.9,
        "usdPerMTok": 1.46,
        "loadsUsed": [
          1,
          20,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 43
      }
    },
    {
      "id": "gpt-oss-120b|A100-40GBx2|sglang|BF16",
      "model": "gpt-oss-120b",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 37.1,
      "cost": 34.9,
      "domains": {
        "chat": 50.7,
        "coding": 35.7,
        "terminal": 38.4,
        "computerUse": 23.7
      },
      "raw": {
        "tpotMs": 74.6,
        "ttftMs": 6226.3,
        "tokPerSec": 190.2,
        "usdPerMTok": 5.81,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 35
      }
    },
    {
      "id": "Qwen3.5-9B|3090|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 35.6,
      "cost": 76.9,
      "domains": {
        "chat": 24.2,
        "coding": 40.1,
        "terminal": 45.2,
        "computerUse": 32.7
      },
      "raw": {
        "tpotMs": 54.1,
        "ttftMs": 10824.2,
        "tokPerSec": 131.2,
        "usdPerMTok": 0.47,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 50
      }
    },
    {
      "id": "Llama-3.1-8B|2080Tix2|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "2080Tix2",
      "hardwareFamily": "2080 Ti",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 34.4,
      "cost": 91,
      "domains": {
        "chat": 56.2,
        "coding": 21.7,
        "terminal": 33.7,
        "computerUse": 25.8
      },
      "raw": {
        "tpotMs": 221.9,
        "ttftMs": 8737.9,
        "tokPerSec": 277.1,
        "usdPerMTok": 0.2,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 46
      }
    },
    {
      "id": "Qwen2.5-72B|A100-40GBx4|vllm|BF16",
      "model": "Qwen2.5-72B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 33.5,
      "cost": 6.9,
      "domains": {
        "chat": 16.7,
        "coding": 43.7,
        "terminal": 49.1,
        "computerUse": 24.5
      },
      "raw": {
        "tpotMs": 37.4,
        "ttftMs": 23872,
        "tokPerSec": 70.5,
        "usdPerMTok": 31.36,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 44
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GBx4|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 33.3,
      "cost": 31.7,
      "domains": {
        "chat": 54.7,
        "coding": 43.2,
        "terminal": 17.6,
        "computerUse": 17.7
      },
      "raw": {
        "tpotMs": 119.7,
        "ttftMs": 7007.3,
        "tokPerSec": 312.6,
        "usdPerMTok": 7.07,
        "loadsUsed": [
          1,
          20,
          40,
          160,
          200
        ],
        "domainCount": 4,
        "runCount": 48
      }
    },
    {
      "id": "Llama-3.1-8B|2080Ti|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "2080Ti",
      "hardwareFamily": "2080 Ti",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 31.8,
      "cost": 89.1,
      "domains": {
        "chat": 29.5,
        "coding": 33,
        "terminal": 35.3,
        "computerUse": 29.5
      },
      "raw": {
        "tpotMs": 52.9,
        "ttftMs": 11088.5,
        "tokPerSec": 124.1,
        "usdPerMTok": 0.22,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 53
      }
    },
    {
      "id": "Llama-3.1-8B|3090x2|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 31.8,
      "cost": 67,
      "domains": {
        "chat": 31.1,
        "coding": 23.1,
        "terminal": 39.2,
        "computerUse": 33.6
      },
      "raw": {
        "tpotMs": 211.2,
        "ttftMs": 9603.2,
        "tokPerSec": 144.6,
        "usdPerMTok": 0.85,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 41
      }
    },
    {
      "id": "Llama-3.1-8B|3090|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 30.8,
      "cost": 85,
      "domains": {
        "chat": 49.9,
        "coding": 19.9,
        "terminal": 34.1,
        "computerUse": 19.4
      },
      "raw": {
        "tpotMs": 126.8,
        "ttftMs": 12139.9,
        "tokPerSec": 213.4,
        "usdPerMTok": 0.29,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 49
      }
    },
    {
      "id": "Llama-3.1-8B|3090|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 30.6,
      "cost": 80.2,
      "domains": {
        "chat": 45.3,
        "coding": 20.9,
        "terminal": 35.2,
        "computerUse": 21
      },
      "raw": {
        "tpotMs": 91.1,
        "ttftMs": 12595,
        "tokPerSec": 159.4,
        "usdPerMTok": 0.38,
        "loadsUsed": [
          1,
          5,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 49
      }
    },
    {
      "id": "Llama-3.1-70B|H100x2|sglang|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 29.4,
      "cost": 23.2,
      "domains": {
        "chat": 45.3,
        "coding": 21.7,
        "terminal": 32,
        "computerUse": 18.6
      },
      "raw": {
        "tpotMs": 86.8,
        "ttftMs": 15715.8,
        "tokPerSec": 187.7,
        "usdPerMTok": 11.81,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 48
      }
    },
    {
      "id": "Llama-3.3-70B|H100x2|sglang|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 29.3,
      "cost": 23.5,
      "domains": {
        "chat": 46.3,
        "coding": 24.2,
        "terminal": 30.4,
        "computerUse": 16.2
      },
      "raw": {
        "tpotMs": 113.4,
        "ttftMs": 17409,
        "tokPerSec": 191.6,
        "usdPerMTok": 11.57,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 46
      }
    },
    {
      "id": "Qwen3.5-9B|3090|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 28.4,
      "cost": 62.5,
      "domains": {
        "chat": 1,
        "coding": 26,
        "terminal": 54.7,
        "computerUse": 31.7
      },
      "raw": {
        "tpotMs": 79.9,
        "ttftMs": 56767.6,
        "tokPerSec": 55.2,
        "usdPerMTok": 1.11,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 42
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GBx2|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 24.8,
      "cost": 1,
      "domains": {
        "chat": 31.2,
        "coding": 8.9,
        "terminal": 26.6,
        "computerUse": 32.4
      },
      "raw": {
        "tpotMs": 207.3,
        "ttftMs": 2462,
        "tokPerSec": 24.7,
        "usdPerMTok": 44.73,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Qwen3.5-27B|A100-40GBx2|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 24.1,
      "cost": 28.9,
      "domains": {
        "chat": 25.7,
        "coding": 14.6,
        "terminal": 31.5,
        "computerUse": 24.7
      },
      "raw": {
        "tpotMs": 164.2,
        "ttftMs": 10606,
        "tokPerSec": 132.2,
        "usdPerMTok": 8.36,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "Qwen3.5-9B|2080Tix2|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "2080Tix2",
      "hardwareFamily": "2080 Ti",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 22.8,
      "cost": 85.1,
      "domains": {
        "chat": 38.5,
        "coding": 15.8,
        "terminal": 22.9,
        "computerUse": 14.2
      },
      "raw": {
        "tpotMs": 311.7,
        "ttftMs": 14940.9,
        "tokPerSec": 194.6,
        "usdPerMTok": 0.29,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 39
      }
    },
    {
      "id": "Qwen3.5-9B|3090x4|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 20.7,
      "cost": 56.5,
      "domains": {
        "chat": 37.7,
        "coding": 26.6,
        "terminal": 17.5,
        "computerUse": 1
      },
      "raw": {
        "tpotMs": 224.9,
        "ttftMs": 4610.5,
        "tokPerSec": 153.5,
        "usdPerMTok": 1.59,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 50
      }
    },
    {
      "id": "Llama-3.1-70B|A100-40GBx4|sglang|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 15.9,
      "cost": 11.8,
      "domains": {
        "chat": 21.1,
        "coding": 17.4,
        "terminal": 14.9,
        "computerUse": 10.3
      },
      "raw": {
        "tpotMs": 149.7,
        "ttftMs": 32808.7,
        "tokPerSec": 94.7,
        "usdPerMTok": 23.35,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 35
      }
    },
    {
      "id": "Qwen3.5-9B|3090x2|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 15.8,
      "cost": 36.2,
      "domains": {
        "chat": 11.2,
        "coding": 10.8,
        "terminal": 14.3,
        "computerUse": 26.7
      },
      "raw": {
        "tpotMs": 319.2,
        "ttftMs": 3373.8,
        "tokPerSec": 22.6,
        "usdPerMTok": 5.4,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.3-70B|A100-40GBx4|sglang|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 15.3,
      "cost": 9.5,
      "domains": {
        "chat": 21.7,
        "coding": 18.2,
        "terminal": 10.5,
        "computerUse": 10.9
      },
      "raw": {
        "tpotMs": 189.8,
        "ttftMs": 40884,
        "tokPerSec": 82.3,
        "usdPerMTok": 26.87,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 30
      }
    },
    {
      "id": "Qwen3.5-27B|3090x4|vllm|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 12,
      "cost": 49.7,
      "domains": {
        "chat": 24.6,
        "coding": 4.2,
        "terminal": 11.4,
        "computerUse": 7.7
      },
      "raw": {
        "tpotMs": 510.9,
        "ttftMs": 18074.8,
        "tokPerSec": 102,
        "usdPerMTok": 2.4,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 41
      }
    },
    {
      "id": "Qwen3.5-27B|A100-40GBx4|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 10.4,
      "cost": 10.5,
      "domains": {
        "chat": 31.2,
        "coding": 1,
        "terminal": 1,
        "computerUse": 8.2
      },
      "raw": {
        "tpotMs": 447.3,
        "ttftMs": 14161.9,
        "tokPerSec": 87.6,
        "usdPerMTok": 25.23,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 50
      }
    },
    {
      "id": "Qwen3.5-27B|3090x4|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 8.5,
      "cost": 39.9,
      "domains": {
        "chat": 11.1,
        "coding": 4.4,
        "terminal": 11.9,
        "computerUse": 6.7
      },
      "raw": {
        "tpotMs": 441.7,
        "ttftMs": 13233,
        "tokPerSec": 56.6,
        "usdPerMTok": 4.32,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 39
      }
    }
  ]
} as EfficiencySnapshot;
