/* Generated by scripts/build-efficiency-index.ts — do not edit by hand. */
import type { DomainScales, IndexRow } from './score';

export interface EfficiencySnapshot {
  version: string;
  generatedAt: string;
  source: string;
  sourceModified: string;
  n: number;
  verified: number;
  estimated: number;
  scales: DomainScales;
  rows: IndexRow[];
}

export const EFFICIENCY_SNAPSHOT: EfficiencySnapshot = {
  "version": "1.0",
  "generatedAt": "2026-09-07",
  "source": "json/current/data.synthetic_distributional.json",
  "sourceModified": "2026-08-30",
  "n": 101,
  "verified": 101,
  "estimated": 0,
  "scales": {
    "chat": {
      "p10": 0.10493498539270033,
      "p90": 1.2136112754524355,
      "max": 1.7235984375142104
    },
    "coding": {
      "p10": 0.022792812917790967,
      "p90": 0.5698452429660519,
      "max": 0.684986521183474
    },
    "terminal": {
      "p10": 0.028817397938153962,
      "p90": 0.5628149835295955,
      "max": 0.7670495525684725
    },
    "computerUse": {
      "p10": 0.04535043267303935,
      "p90": 0.7081157998000549,
      "max": 0.9430401499153881
    },
    "cost": {
      "p10": 86427.17138935933,
      "p90": 2529788.5685262154,
      "max": 8582549.192720909
    }
  },
  "rows": [
    {
      "id": "Llama-3.1-8B|H100x4|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 99,
      "cost": 35.3,
      "domains": {
        "chat": 100,
        "coding": 95.9,
        "terminal": 100,
        "computerUse": 100
      },
      "raw": {
        "tpotMs": 5.2,
        "ttftMs": 414.7,
        "tokPerSec": 1946.2,
        "usdPerMTok": 2.28,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GBx4|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 96.7,
      "cost": 47,
      "domains": {
        "chat": 94.9,
        "coding": 98.1,
        "terminal": 94.5,
        "computerUse": 99.1
      },
      "raw": {
        "tpotMs": 7.2,
        "ttftMs": 263.1,
        "tokPerSec": 1660.3,
        "usdPerMTok": 1.33,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100x2|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 95.7,
      "cost": 45.9,
      "domains": {
        "chat": 90.5,
        "coding": 99.9,
        "terminal": 94.7,
        "computerUse": 97.7
      },
      "raw": {
        "tpotMs": 6.1,
        "ttftMs": 311.2,
        "tokPerSec": 1579,
        "usdPerMTok": 1.4,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|H100x4|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 94.7,
      "cost": 29.2,
      "domains": {
        "chat": 88.8,
        "coding": 100,
        "terminal": 94.5,
        "computerUse": 95.3
      },
      "raw": {
        "tpotMs": 7.8,
        "ttftMs": 269.5,
        "tokPerSec": 1465.1,
        "usdPerMTok": 3.03,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 93.1,
      "cost": 58.9,
      "domains": {
        "chat": 87,
        "coding": 98.7,
        "terminal": 92.9,
        "computerUse": 93.8
      },
      "raw": {
        "tpotMs": 6.8,
        "ttftMs": 365,
        "tokPerSec": 1435.9,
        "usdPerMTok": 0.77,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100x4|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 92.2,
      "cost": 34.1,
      "domains": {
        "chat": 90.5,
        "coding": 98.5,
        "terminal": 91.3,
        "computerUse": 88.3
      },
      "raw": {
        "tpotMs": 5,
        "ttftMs": 405.1,
        "tokPerSec": 1836.7,
        "usdPerMTok": 2.41,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100x4|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 91.2,
      "cost": 33.4,
      "domains": {
        "chat": 97.1,
        "coding": 83.9,
        "terminal": 88.1,
        "computerUse": 95.5
      },
      "raw": {
        "tpotMs": 6.1,
        "ttftMs": 544.7,
        "tokPerSec": 1780.5,
        "usdPerMTok": 2.49,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 90.7,
      "cost": 58.4,
      "domains": {
        "chat": 79.1,
        "coding": 97,
        "terminal": 94.5,
        "computerUse": 92.3
      },
      "raw": {
        "tpotMs": 7.4,
        "ttftMs": 425.6,
        "tokPerSec": 1404.2,
        "usdPerMTok": 0.79,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GBx2|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 90.6,
      "cost": 56.9,
      "domains": {
        "chat": 88,
        "coding": 94.6,
        "terminal": 87.9,
        "computerUse": 91.8
      },
      "raw": {
        "tpotMs": 10.7,
        "ttftMs": 273.1,
        "tokPerSec": 1307.8,
        "usdPerMTok": 0.85,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100x4|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 90.5,
      "cost": 34.1,
      "domains": {
        "chat": 89.6,
        "coding": 89.7,
        "terminal": 86.9,
        "computerUse": 95.7
      },
      "raw": {
        "tpotMs": 7.6,
        "ttftMs": 396.5,
        "tokPerSec": 1836.7,
        "usdPerMTok": 2.41,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|H100x2|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 89.8,
      "cost": 46.7,
      "domains": {
        "chat": 87.5,
        "coding": 95.9,
        "terminal": 90.7,
        "computerUse": 85.2
      },
      "raw": {
        "tpotMs": 5.9,
        "ttftMs": 406.7,
        "tokPerSec": 1641.5,
        "usdPerMTok": 1.35,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|H100x2|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 89.8,
      "cost": 39.6,
      "domains": {
        "chat": 83.6,
        "coding": 94.6,
        "terminal": 90.6,
        "computerUse": 90.5
      },
      "raw": {
        "tpotMs": 10.2,
        "ttftMs": 279.5,
        "tokPerSec": 1184.7,
        "usdPerMTok": 1.87,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|H100x4|vllm|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 89.7,
      "cost": 22.6,
      "domains": {
        "chat": 82.9,
        "coding": 94.5,
        "terminal": 91.3,
        "computerUse": 90.1
      },
      "raw": {
        "tpotMs": 10.5,
        "ttftMs": 325.5,
        "tokPerSec": 1084.7,
        "usdPerMTok": 4.09,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100x2|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 88.8,
      "cost": 45.6,
      "domains": {
        "chat": 94.7,
        "coding": 78.7,
        "terminal": 90.3,
        "computerUse": 91.5
      },
      "raw": {
        "tpotMs": 7.7,
        "ttftMs": 416.6,
        "tokPerSec": 1556.3,
        "usdPerMTok": 1.42,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|H100x2|sglang|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 88.2,
      "cost": 39.7,
      "domains": {
        "chat": 75.7,
        "coding": 95.6,
        "terminal": 94.2,
        "computerUse": 87.2
      },
      "raw": {
        "tpotMs": 9.8,
        "ttftMs": 326.9,
        "tokPerSec": 1188.4,
        "usdPerMTok": 1.87,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100x2|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 85.8,
      "cost": 44.9,
      "domains": {
        "chat": 84.4,
        "coding": 84.5,
        "terminal": 84,
        "computerUse": 90.2
      },
      "raw": {
        "tpotMs": 8.9,
        "ttftMs": 423.1,
        "tokPerSec": 1507.6,
        "usdPerMTok": 1.47,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-120b|A100-40GBx4|vllm|BF16",
      "model": "gpt-oss-120b",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 85.5,
      "cost": 38.2,
      "domains": {
        "chat": 80.4,
        "coding": 88.8,
        "terminal": 84.9,
        "computerUse": 87.8
      },
      "raw": {
        "tpotMs": 12.7,
        "ttftMs": 294,
        "tokPerSec": 1108.8,
        "usdPerMTok": 1.99,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|H100x4|sglang|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 83.1,
      "cost": 24,
      "domains": {
        "chat": 80.6,
        "coding": 88,
        "terminal": 87.2,
        "computerUse": 76.4
      },
      "raw": {
        "tpotMs": 10,
        "ttftMs": 511.5,
        "tokPerSec": 1153.6,
        "usdPerMTok": 3.84,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|A100-40GBx4|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 82.9,
      "cost": 35.5,
      "domains": {
        "chat": 77.2,
        "coding": 87.6,
        "terminal": 83.7,
        "computerUse": 83.1
      },
      "raw": {
        "tpotMs": 13.8,
        "ttftMs": 320.7,
        "tokPerSec": 975.8,
        "usdPerMTok": 2.27,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100x2|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 82.4,
      "cost": 45,
      "domains": {
        "chat": 91.9,
        "coding": 69.1,
        "terminal": 80.9,
        "computerUse": 87.8
      },
      "raw": {
        "tpotMs": 8.4,
        "ttftMs": 532.6,
        "tokPerSec": 1514.1,
        "usdPerMTok": 1.46,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|H100x4|sglang|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 81,
      "cost": 17.1,
      "domains": {
        "chat": 66.2,
        "coding": 91.7,
        "terminal": 85,
        "computerUse": 81
      },
      "raw": {
        "tpotMs": 14.4,
        "ttftMs": 422.4,
        "tokPerSec": 842.1,
        "usdPerMTok": 5.26,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GBx4|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 80.2,
      "cost": 41.3,
      "domains": {
        "chat": 87.2,
        "coding": 69.5,
        "terminal": 78.2,
        "computerUse": 86
      },
      "raw": {
        "tpotMs": 11.6,
        "ttftMs": 427.8,
        "tokPerSec": 1276,
        "usdPerMTok": 1.73,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GBx4|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 78,
      "cost": 40.4,
      "domains": {
        "chat": 77.8,
        "coding": 75.3,
        "terminal": 75.5,
        "computerUse": 83.5
      },
      "raw": {
        "tpotMs": 11.4,
        "ttftMs": 534.5,
        "tokPerSec": 1224.2,
        "usdPerMTok": 1.81,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 75.7,
      "cost": 54.7,
      "domains": {
        "chat": 86.8,
        "coding": 63.4,
        "terminal": 73.4,
        "computerUse": 79.3
      },
      "raw": {
        "tpotMs": 12.3,
        "ttftMs": 424.2,
        "tokPerSec": 1183,
        "usdPerMTok": 0.94,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|H100x2|vllm|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 75.5,
      "cost": 28.6,
      "domains": {
        "chat": 71.2,
        "coding": 79.8,
        "terminal": 76.4,
        "computerUse": 74.7
      },
      "raw": {
        "tpotMs": 18.1,
        "ttftMs": 373.8,
        "tokPerSec": 713.7,
        "usdPerMTok": 3.11,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|H100x2|sglang|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 73.9,
      "cost": 28.2,
      "domains": {
        "chat": 69,
        "coding": 78.6,
        "terminal": 76.5,
        "computerUse": 71.3
      },
      "raw": {
        "tpotMs": 18.2,
        "ttftMs": 445,
        "tokPerSec": 701.7,
        "usdPerMTok": 3.16,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|H100|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 72.9,
      "cost": 53.1,
      "domains": {
        "chat": 82.1,
        "coding": 62.2,
        "terminal": 70.7,
        "computerUse": 76.6
      },
      "raw": {
        "tpotMs": 11.8,
        "ttftMs": 534.3,
        "tokPerSec": 1100.9,
        "usdPerMTok": 1.01,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|A100-40GBx4|sglang|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 71.1,
      "cost": 30.2,
      "domains": {
        "chat": 65.9,
        "coding": 74.7,
        "terminal": 73.8,
        "computerUse": 69.8
      },
      "raw": {
        "tpotMs": 14.2,
        "ttftMs": 727.6,
        "tokPerSec": 766.8,
        "usdPerMTok": 2.88,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 70.5,
      "cost": 53,
      "domains": {
        "chat": 71.1,
        "coding": 62.7,
        "terminal": 67.7,
        "computerUse": 80.6
      },
      "raw": {
        "tpotMs": 13.5,
        "ttftMs": 584.4,
        "tokPerSec": 1094.3,
        "usdPerMTok": 1.01,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-27B|H100x4|vllm|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 69.9,
      "cost": 19.8,
      "domains": {
        "chat": 67.5,
        "coding": 68.2,
        "terminal": 68.5,
        "computerUse": 75.3
      },
      "raw": {
        "tpotMs": 16.6,
        "ttftMs": 585.6,
        "tokPerSec": 951.3,
        "usdPerMTok": 4.66,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|3090x4|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 66.9,
      "cost": 74.4,
      "domains": {
        "chat": 63.1,
        "coding": 71.5,
        "terminal": 65,
        "computerUse": 68.1
      },
      "raw": {
        "tpotMs": 26.4,
        "ttftMs": 612.7,
        "tokPerSec": 646.4,
        "usdPerMTok": 0.38,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GB|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 65.1,
      "cost": 64,
      "domains": {
        "chat": 74.6,
        "coding": 53.5,
        "terminal": 63,
        "computerUse": 69.3
      },
      "raw": {
        "tpotMs": 22.2,
        "ttftMs": 586.2,
        "tokPerSec": 908.1,
        "usdPerMTok": 0.61,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GBx2|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 64.5,
      "cost": 48.4,
      "domains": {
        "chat": 77.3,
        "coding": 51.1,
        "terminal": 64.1,
        "computerUse": 65.6
      },
      "raw": {
        "tpotMs": 20.4,
        "ttftMs": 485.2,
        "tokPerSec": 884.4,
        "usdPerMTok": 1.25,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|3090x2|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 62.4,
      "cost": 89.2,
      "domains": {
        "chat": 62.3,
        "coding": 67.4,
        "terminal": 59.5,
        "computerUse": 60.3
      },
      "raw": {
        "tpotMs": 25.6,
        "ttftMs": 610,
        "tokPerSec": 639.7,
        "usdPerMTok": 0.19,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GBx4|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 60.9,
      "cost": 30.5,
      "domains": {
        "chat": 74.2,
        "coding": 59.4,
        "terminal": 43.7,
        "computerUse": 66.1
      },
      "raw": {
        "tpotMs": 27.2,
        "ttftMs": 1372.5,
        "tokPerSec": 775.1,
        "usdPerMTok": 2.85,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 46
      }
    },
    {
      "id": "Qwen3.5-9B|H100x4|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 59.7,
      "cost": 20.5,
      "domains": {
        "chat": 70.1,
        "coding": 54.8,
        "terminal": 50.2,
        "computerUse": 63.5
      },
      "raw": {
        "tpotMs": 26.8,
        "ttftMs": 1068.9,
        "tokPerSec": 984.5,
        "usdPerMTok": 4.5,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|A100-40GBx2|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 59.2,
      "cost": 41.3,
      "domains": {
        "chat": 64.5,
        "coding": 59.5,
        "terminal": 44.5,
        "computerUse": 68.1
      },
      "raw": {
        "tpotMs": 27.2,
        "ttftMs": 534.3,
        "tokPerSec": 638.1,
        "usdPerMTok": 1.73,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Mixtral-8x7B|A100-40GBx4|vllm|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 57.4,
      "cost": 23.3,
      "domains": {
        "chat": 66.4,
        "coding": 46,
        "terminal": 59.2,
        "computerUse": 57.8
      },
      "raw": {
        "tpotMs": 30.7,
        "ttftMs": 563.5,
        "tokPerSec": 556.7,
        "usdPerMTok": 3.97,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 56.3,
      "cost": 46.6,
      "domains": {
        "chat": 62.2,
        "coding": 45.8,
        "terminal": 51.2,
        "computerUse": 65.8
      },
      "raw": {
        "tpotMs": 28.2,
        "ttftMs": 1044.4,
        "tokPerSec": 817,
        "usdPerMTok": 1.36,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GBx2|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 55,
      "cost": 42.8,
      "domains": {
        "chat": 66.9,
        "coding": 45.5,
        "terminal": 49.5,
        "computerUse": 58.1
      },
      "raw": {
        "tpotMs": 38.9,
        "ttftMs": 965.6,
        "tokPerSec": 684,
        "usdPerMTok": 1.62,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 49
      }
    },
    {
      "id": "Llama-3.1-70B|H100x4|vllm|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 54.7,
      "cost": 10.3,
      "domains": {
        "chat": 63,
        "coding": 41.8,
        "terminal": 53.5,
        "computerUse": 60.6
      },
      "raw": {
        "tpotMs": 25.4,
        "ttftMs": 600.6,
        "tokPerSec": 616.6,
        "usdPerMTok": 7.19,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.3-70B|H100x4|vllm|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 54.2,
      "cost": 9.2,
      "domains": {
        "chat": 60,
        "coding": 42.8,
        "terminal": 53.4,
        "computerUse": 60.5
      },
      "raw": {
        "tpotMs": 25.5,
        "ttftMs": 592.6,
        "tokPerSec": 583.6,
        "usdPerMTok": 7.6,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-27B|H100x2|vllm|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 53.4,
      "cost": 27.1,
      "domains": {
        "chat": 56.5,
        "coding": 47.8,
        "terminal": 47.4,
        "computerUse": 61.8
      },
      "raw": {
        "tpotMs": 24.5,
        "ttftMs": 919.1,
        "tokPerSec": 666,
        "usdPerMTok": 3.33,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen2.5-72B|H100x4|vllm|BF16",
      "model": "Qwen2.5-72B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 53.1,
      "cost": 9.5,
      "domains": {
        "chat": 62.7,
        "coding": 39.8,
        "terminal": 51.2,
        "computerUse": 58.6
      },
      "raw": {
        "tpotMs": 26.8,
        "ttftMs": 663.6,
        "tokPerSec": 594,
        "usdPerMTok": 7.46,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GB|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 51.7,
      "cost": 54.2,
      "domains": {
        "chat": 47.4,
        "coding": 57,
        "terminal": 53.3,
        "computerUse": 49.2
      },
      "raw": {
        "tpotMs": 24.9,
        "ttftMs": 781.7,
        "tokPerSec": 578,
        "usdPerMTok": 0.96,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|3090|vllm|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 51.6,
      "cost": 100,
      "domains": {
        "chat": 54.6,
        "coding": 51.8,
        "terminal": 46.5,
        "computerUse": 53.3
      },
      "raw": {
        "tpotMs": 26.6,
        "ttftMs": 1017.9,
        "tokPerSec": 524.5,
        "usdPerMTok": 0.12,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|A100-40GBx2|sglang|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 49.3,
      "cost": 34.8,
      "domains": {
        "chat": 46.6,
        "coding": 50.8,
        "terminal": 48.3,
        "computerUse": 51.4
      },
      "raw": {
        "tpotMs": 37.6,
        "ttftMs": 849.9,
        "tokPerSec": 473.3,
        "usdPerMTok": 2.34,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GBx2|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 47.8,
      "cost": 46.6,
      "domains": {
        "chat": 69.1,
        "coding": 56.5,
        "terminal": 45.5,
        "computerUse": 19.9
      },
      "raw": {
        "tpotMs": 22.9,
        "ttftMs": 755.2,
        "tokPerSec": 812.7,
        "usdPerMTok": 1.36,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GB|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 46.4,
      "cost": 49.7,
      "domains": {
        "chat": 38.6,
        "coding": 49.4,
        "terminal": 49,
        "computerUse": 48.6
      },
      "raw": {
        "tpotMs": 36.3,
        "ttftMs": 921.5,
        "tokPerSec": 469.6,
        "usdPerMTok": 1.18,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.3-70B|H100x4|sglang|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 45.2,
      "cost": 5.4,
      "domains": {
        "chat": 52.9,
        "coding": 47.8,
        "terminal": 36.9,
        "computerUse": 43.1
      },
      "raw": {
        "tpotMs": 27.4,
        "ttftMs": 1956.3,
        "tokPerSec": 490.8,
        "usdPerMTok": 9.03,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 43
      }
    },
    {
      "id": "Llama-3.1-70B|H100x4|sglang|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 45.1,
      "cost": 5.8,
      "domains": {
        "chat": 53.3,
        "coding": 48.3,
        "terminal": 34.9,
        "computerUse": 43.8
      },
      "raw": {
        "tpotMs": 26.5,
        "ttftMs": 2138.4,
        "tokPerSec": 501.1,
        "usdPerMTok": 8.85,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 43
      }
    },
    {
      "id": "Qwen2.5-72B|H100x4|sglang|BF16",
      "model": "Qwen2.5-72B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 44.5,
      "cost": 4.2,
      "domains": {
        "chat": 50.5,
        "coding": 48,
        "terminal": 35.9,
        "computerUse": 43.4
      },
      "raw": {
        "tpotMs": 27.8,
        "ttftMs": 2051.8,
        "tokPerSec": 464.9,
        "usdPerMTok": 9.54,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 43
      }
    },
    {
      "id": "Mixtral-8x7B|A100-40GBx4|sglang|BF16",
      "model": "Mixtral-8x7B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 43.8,
      "cost": 19.2,
      "domains": {
        "chat": 54.4,
        "coding": 42.1,
        "terminal": 39.6,
        "computerUse": 39.3
      },
      "raw": {
        "tpotMs": 28.4,
        "ttftMs": 1517,
        "tokPerSec": 462.2,
        "usdPerMTok": 4.78,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "gpt-oss-120b|A100-40GBx4|sglang|BF16",
      "model": "gpt-oss-120b",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 41.3,
      "cost": 16.1,
      "domains": {
        "chat": 54.9,
        "coding": 38.5,
        "terminal": 38.7,
        "computerUse": 33.2
      },
      "raw": {
        "tpotMs": 33.2,
        "ttftMs": 3047.9,
        "tokPerSec": 401.2,
        "usdPerMTok": 5.51,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GB|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 40.5,
      "cost": 52.4,
      "domains": {
        "chat": 61.6,
        "coding": 20.6,
        "terminal": 41.7,
        "computerUse": 38.1
      },
      "raw": {
        "tpotMs": 69.1,
        "ttftMs": 1936.5,
        "tokPerSec": 531.8,
        "usdPerMTok": 1.04,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3-30B-A3B|3090x4|vllm|BF16",
      "model": "Qwen3-30B-A3B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 40.4,
      "cost": 60.5,
      "domains": {
        "chat": 39.9,
        "coding": 43.9,
        "terminal": 35.7,
        "computerUse": 42
      },
      "raw": {
        "tpotMs": 50.3,
        "ttftMs": 1064,
        "tokPerSec": 341.4,
        "usdPerMTok": 0.72,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|A100-40GB|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 39.9,
      "cost": 51.4,
      "domains": {
        "chat": 58.2,
        "coding": 22.5,
        "terminal": 38.1,
        "computerUse": 40.8
      },
      "raw": {
        "tpotMs": 63,
        "ttftMs": 2428.9,
        "tokPerSec": 507.3,
        "usdPerMTok": 1.09,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-8B|3090x4|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 39.5,
      "cost": 65.5,
      "domains": {
        "chat": 51.4,
        "coding": 26.7,
        "terminal": 36.8,
        "computerUse": 43.1
      },
      "raw": {
        "tpotMs": 51.2,
        "ttftMs": 1252.3,
        "tokPerSec": 429.7,
        "usdPerMTok": 0.57,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 48
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GBx2|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 36.4,
      "cost": 26.7,
      "domains": {
        "chat": 45.4,
        "coding": 37.1,
        "terminal": 32.3,
        "computerUse": 30.6
      },
      "raw": {
        "tpotMs": 53.3,
        "ttftMs": 3491.8,
        "tokPerSec": 325.8,
        "usdPerMTok": 3.39,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "gpt-oss-120b|3090x4|vllm|BF16",
      "model": "gpt-oss-120b",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 35.9,
      "cost": 61.4,
      "domains": {
        "chat": 35.7,
        "coding": 40.2,
        "terminal": 30.4,
        "computerUse": 37.4
      },
      "raw": {
        "tpotMs": 50.9,
        "ttftMs": 1300.5,
        "tokPerSec": 355.4,
        "usdPerMTok": 0.69,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-27B|H100x2|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 34.9,
      "cost": 15,
      "domains": {
        "chat": 35.7,
        "coding": 34.3,
        "terminal": 29.1,
        "computerUse": 40.4
      },
      "raw": {
        "tpotMs": 48,
        "ttftMs": 1976.8,
        "tokPerSec": 382.1,
        "usdPerMTok": 5.8,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-27B|H100x4|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100x4",
      "hardwareFamily": "H100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 32.4,
      "cost": 0,
      "domains": {
        "chat": 28.9,
        "coding": 32.5,
        "terminal": 27.7,
        "computerUse": 40.6
      },
      "raw": {
        "tpotMs": 62,
        "ttftMs": 2363.7,
        "tokPerSec": 254.9,
        "usdPerMTok": 17.4,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GBx4|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 31.1,
      "cost": 18.5,
      "domains": {
        "chat": 41.9,
        "coding": 13.9,
        "terminal": 21.2,
        "computerUse": 47.4
      },
      "raw": {
        "tpotMs": 100.3,
        "ttftMs": 3065,
        "tokPerSec": 447.2,
        "usdPerMTok": 4.94,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 53
      }
    },
    {
      "id": "Llama-3.1-8B|3090x4|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 31,
      "cost": 52,
      "domains": {
        "chat": 27.1,
        "coding": 37.9,
        "terminal": 29.6,
        "computerUse": 29.2
      },
      "raw": {
        "tpotMs": 80.4,
        "ttftMs": 1698.4,
        "tokPerSec": 230.4,
        "usdPerMTok": 1.06,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 42
      }
    },
    {
      "id": "Qwen3.5-9B|3090x4|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 29.9,
      "cost": 57.5,
      "domains": {
        "chat": 35.6,
        "coding": 36.4,
        "terminal": 29.4,
        "computerUse": 18.2
      },
      "raw": {
        "tpotMs": 80.3,
        "ttftMs": 2645.7,
        "tokPerSec": 297.4,
        "usdPerMTok": 0.82,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-9B|H100x2|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 29.2,
      "cost": 0,
      "domains": {
        "chat": 26.4,
        "coding": 28.2,
        "terminal": 28.6,
        "computerUse": 33.8
      },
      "raw": {
        "tpotMs": 54,
        "ttftMs": 915,
        "tokPerSec": 68.8,
        "usdPerMTok": 32.21,
        "loadsUsed": [
          1,
          5,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "gpt-oss-20b|3090x2|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 28.8,
      "cost": 59.8,
      "domains": {
        "chat": 15.6,
        "coding": 39.5,
        "terminal": 35.4,
        "computerUse": 24.6
      },
      "raw": {
        "tpotMs": 128,
        "ttftMs": 1597.1,
        "tokPerSec": 165.2,
        "usdPerMTok": 0.74,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "Qwen2.5-72B|H100x2|sglang|BF16",
      "model": "Qwen2.5-72B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 27.3,
      "cost": 9.2,
      "domains": {
        "chat": 20.1,
        "coding": 61.7,
        "terminal": 0,
        "computerUse": null
      },
      "raw": {
        "tpotMs": 115.7,
        "ttftMs": 2478.7,
        "tokPerSec": 292.2,
        "usdPerMTok": 7.59,
        "loadsUsed": [
          1,
          40,
          80,
          160
        ],
        "domainCount": 3,
        "runCount": 27
      }
    },
    {
      "id": "gpt-oss-20b|3090x4|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 26.5,
      "cost": 51.9,
      "domains": {
        "chat": 31.6,
        "coding": 31.5,
        "terminal": 25.1,
        "computerUse": 17.7
      },
      "raw": {
        "tpotMs": 90.8,
        "ttftMs": 1291,
        "tokPerSec": 229.6,
        "usdPerMTok": 1.06,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Qwen3.5-9B|2080Tix4|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "2080Tix4",
      "hardwareFamily": "2080 Ti",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 25.7,
      "cost": 73.4,
      "domains": {
        "chat": 24.5,
        "coding": 32.5,
        "terminal": 15.3,
        "computerUse": 30.4
      },
      "raw": {
        "tpotMs": 107.7,
        "ttftMs": 3408.7,
        "tokPerSec": 281.1,
        "usdPerMTok": 0.4,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 41
      }
    },
    {
      "id": "Qwen3.5-27B|H100|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 25.1,
      "cost": 21.6,
      "domains": {
        "chat": 12.1,
        "coding": 29.9,
        "terminal": 24.9,
        "computerUse": 33.5
      },
      "raw": {
        "tpotMs": 63.4,
        "ttftMs": 4129.6,
        "tokPerSec": 259.1,
        "usdPerMTok": 4.28,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 53
      }
    },
    {
      "id": "gpt-oss-20b|3090|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 22.4,
      "cost": 77.2,
      "domains": {
        "chat": 18.6,
        "coding": 26.8,
        "terminal": 20.1,
        "computerUse": 23.9
      },
      "raw": {
        "tpotMs": 117.2,
        "ttftMs": 1815.1,
        "tokPerSec": 184,
        "usdPerMTok": 0.33,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "Llama-3.1-8B|3090x2|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 22.4,
      "cost": 74.4,
      "domains": {
        "chat": 44.1,
        "coding": 0,
        "terminal": 19.5,
        "computerUse": 25.8
      },
      "raw": {
        "tpotMs": 146.5,
        "ttftMs": 5998,
        "tokPerSec": 322.6,
        "usdPerMTok": 0.38,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "Qwen3.5-27B|H100|vllm|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "H100",
      "hardwareFamily": "H100",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 20,
      "cost": 26.1,
      "domains": {
        "chat": 28.6,
        "coding": 10.3,
        "terminal": 17.6,
        "computerUse": 23.3
      },
      "raw": {
        "tpotMs": 121.2,
        "ttftMs": 5015.1,
        "tokPerSec": 317.5,
        "usdPerMTok": 3.49,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GB|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GB",
      "hardwareFamily": "A100",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 19.7,
      "cost": 37.5,
      "domains": {
        "chat": 36.4,
        "coding": 23,
        "terminal": 7.4,
        "computerUse": 11.9
      },
      "raw": {
        "tpotMs": 67.9,
        "ttftMs": 5604.2,
        "tokPerSec": 268.1,
        "usdPerMTok": 2.06,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 40
      }
    },
    {
      "id": "Qwen3.5-9B|3090x2|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 18,
      "cost": 73.1,
      "domains": {
        "chat": 31.9,
        "coding": 1.3,
        "terminal": 17.3,
        "computerUse": 21.3
      },
      "raw": {
        "tpotMs": 129.1,
        "ttftMs": 4647,
        "tokPerSec": 304.9,
        "usdPerMTok": 0.4,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 48
      }
    },
    {
      "id": "Llama-3.3-70B|A100-40GBx4|vllm|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 17.3,
      "cost": 0,
      "domains": {
        "chat": 10.1,
        "coding": 22,
        "terminal": 17.4,
        "computerUse": 19.5
      },
      "raw": {
        "tpotMs": 59.7,
        "ttftMs": 5922.6,
        "tokPerSec": 170.4,
        "usdPerMTok": 12.97,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Llama-3.1-70B|A100-40GBx4|vllm|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 17.1,
      "cost": 0,
      "domains": {
        "chat": 11.8,
        "coding": 21.4,
        "terminal": 16.3,
        "computerUse": 19
      },
      "raw": {
        "tpotMs": 62.8,
        "ttftMs": 5734.5,
        "tokPerSec": 169.5,
        "usdPerMTok": 13.04,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "gpt-oss-120b|A100-40GBx2|sglang|BF16",
      "model": "gpt-oss-120b",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 16.7,
      "cost": 15,
      "domains": {
        "chat": 28.5,
        "coding": 19.8,
        "terminal": 13,
        "computerUse": 5.4
      },
      "raw": {
        "tpotMs": 74.6,
        "ttftMs": 6226.3,
        "tokPerSec": 190.2,
        "usdPerMTok": 5.81,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 35
      }
    },
    {
      "id": "gpt-oss-120b|3090x4|sglang|BF16",
      "model": "gpt-oss-120b",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 16.1,
      "cost": 45.1,
      "domains": {
        "chat": 10,
        "coding": 22.4,
        "terminal": 15.4,
        "computerUse": 16.5
      },
      "raw": {
        "tpotMs": 90.5,
        "ttftMs": 2095,
        "tokPerSec": 167.9,
        "usdPerMTok": 1.46,
        "loadsUsed": [
          1,
          20,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 43
      }
    },
    {
      "id": "Qwen2.5-72B|A100-40GBx4|vllm|BF16",
      "model": "Qwen2.5-72B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 16.1,
      "cost": 0,
      "domains": {
        "chat": 0,
        "coding": 29.7,
        "terminal": 28.1,
        "computerUse": 6.4
      },
      "raw": {
        "tpotMs": 37.4,
        "ttftMs": 23872,
        "tokPerSec": 70.5,
        "usdPerMTok": 31.36,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 44
      }
    },
    {
      "id": "Qwen3.5-9B|3090|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 16.1,
      "cost": 69.9,
      "domains": {
        "chat": 0,
        "coding": 25.3,
        "terminal": 22.7,
        "computerUse": 16.5
      },
      "raw": {
        "tpotMs": 54.1,
        "ttftMs": 10824.2,
        "tokPerSec": 131.2,
        "usdPerMTok": 0.47,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 50
      }
    },
    {
      "id": "gpt-oss-20b|A100-40GBx4|sglang|BF16",
      "model": "gpt-oss-20b",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 15.9,
      "cost": 10.7,
      "domains": {
        "chat": 34.3,
        "coding": 29.1,
        "terminal": 0,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 119.7,
        "ttftMs": 7007.3,
        "tokPerSec": 312.6,
        "usdPerMTok": 7.07,
        "loadsUsed": [
          1,
          20,
          40,
          160,
          200
        ],
        "domainCount": 4,
        "runCount": 48
      }
    },
    {
      "id": "Qwen3.5-9B|3090|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 14.8,
      "cost": 51,
      "domains": {
        "chat": 0,
        "coding": 7.7,
        "terminal": 36.1,
        "computerUse": 15.3
      },
      "raw": {
        "tpotMs": 79.9,
        "ttftMs": 56767.6,
        "tokPerSec": 55.2,
        "usdPerMTok": 1.11,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 42
      }
    },
    {
      "id": "Llama-3.1-8B|2080Tix2|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "2080Tix2",
      "hardwareFamily": "2080 Ti",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 13.3,
      "cost": 88.2,
      "domains": {
        "chat": 36.5,
        "coding": 2.3,
        "terminal": 6.5,
        "computerUse": 8
      },
      "raw": {
        "tpotMs": 221.9,
        "ttftMs": 8737.9,
        "tokPerSec": 277.1,
        "usdPerMTok": 0.2,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 46
      }
    },
    {
      "id": "Llama-3.1-8B|2080Ti|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "2080Ti",
      "hardwareFamily": "2080 Ti",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 9.4,
      "cost": 85.8,
      "domains": {
        "chat": 0,
        "coding": 16.3,
        "terminal": 8.8,
        "computerUse": 12.6
      },
      "raw": {
        "tpotMs": 52.9,
        "ttftMs": 11088.5,
        "tokPerSec": 124.1,
        "usdPerMTok": 0.22,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 53
      }
    },
    {
      "id": "Llama-3.1-8B|3090x2|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 9,
      "cost": 56.9,
      "domains": {
        "chat": 0,
        "coding": 4,
        "terminal": 14.2,
        "computerUse": 17.6
      },
      "raw": {
        "tpotMs": 211.2,
        "ttftMs": 9603.2,
        "tokPerSec": 144.6,
        "usdPerMTok": 0.85,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 41
      }
    },
    {
      "id": "Llama-3.1-8B|3090|sglang|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 8.6,
      "cost": 80.4,
      "domains": {
        "chat": 27.3,
        "coding": 0,
        "terminal": 7,
        "computerUse": 0.1
      },
      "raw": {
        "tpotMs": 126.8,
        "ttftMs": 12139.9,
        "tokPerSec": 213.4,
        "usdPerMTok": 0.29,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 49
      }
    },
    {
      "id": "Llama-3.1-8B|3090|vllm|BF16",
      "model": "Llama-3.1-8B",
      "hardware": "3090",
      "hardwareFamily": "3090",
      "gpus": 1,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 8.2,
      "cost": 74.1,
      "domains": {
        "chat": 20.7,
        "coding": 1.4,
        "terminal": 8.6,
        "computerUse": 2.1
      },
      "raw": {
        "tpotMs": 91.1,
        "ttftMs": 12595,
        "tokPerSec": 159.4,
        "usdPerMTok": 0.38,
        "loadsUsed": [
          1,
          5,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 49
      }
    },
    {
      "id": "Llama-3.3-70B|H100x2|sglang|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 7.3,
      "cost": 0,
      "domains": {
        "chat": 22.1,
        "coding": 5.4,
        "terminal": 1.8,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 113.4,
        "ttftMs": 17409,
        "tokPerSec": 191.6,
        "usdPerMTok": 11.57,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 46
      }
    },
    {
      "id": "Llama-3.1-70B|H100x2|sglang|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "H100x2",
      "hardwareFamily": "H100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 6.8,
      "cost": 0,
      "domains": {
        "chat": 20.6,
        "coding": 2.3,
        "terminal": 4.1,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 86.8,
        "ttftMs": 15715.8,
        "tokPerSec": 187.7,
        "usdPerMTok": 11.81,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 48
      }
    },
    {
      "id": "Qwen3.5-9B|3090x4|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 4.5,
      "cost": 43.1,
      "domains": {
        "chat": 9.7,
        "coding": 8.4,
        "terminal": 0,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 224.9,
        "ttftMs": 4610.5,
        "tokPerSec": 153.5,
        "usdPerMTok": 1.59,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 50
      }
    },
    {
      "id": "Qwen3.5-9B|A100-40GBx2|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 4.1,
      "cost": 0,
      "domains": {
        "chat": 0.2,
        "coding": 0,
        "terminal": 0,
        "computerUse": 16.2
      },
      "raw": {
        "tpotMs": 207.3,
        "ttftMs": 2462,
        "tokPerSec": 24.7,
        "usdPerMTok": 44.73,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 54
      }
    },
    {
      "id": "Qwen3.5-9B|2080Tix2|vllm|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "2080Tix2",
      "hardwareFamily": "2080 Ti",
      "gpus": 2,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 2.7,
      "cost": 80.5,
      "domains": {
        "chat": 10.7,
        "coding": 0,
        "terminal": 0,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 311.7,
        "ttftMs": 14940.9,
        "tokPerSec": 194.6,
        "usdPerMTok": 0.29,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 39
      }
    },
    {
      "id": "Qwen3.5-27B|A100-40GBx2|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "A100-40GBx2",
      "hardwareFamily": "A100",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 2.5,
      "cost": 7.1,
      "domains": {
        "chat": 0,
        "coding": 0,
        "terminal": 3.3,
        "computerUse": 6.7
      },
      "raw": {
        "tpotMs": 164.2,
        "ttftMs": 10606,
        "tokPerSec": 132.2,
        "usdPerMTok": 8.36,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 52
      }
    },
    {
      "id": "Qwen3.5-9B|3090x2|sglang|BF16",
      "model": "Qwen3.5-9B",
      "hardware": "3090x2",
      "hardwareFamily": "3090",
      "gpus": 2,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 2.3,
      "cost": 16.6,
      "domains": {
        "chat": 0,
        "coding": 0,
        "terminal": 0,
        "computerUse": 9.1
      },
      "raw": {
        "tpotMs": 319.2,
        "ttftMs": 3373.8,
        "tokPerSec": 22.6,
        "usdPerMTok": 5.4,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 55
      }
    },
    {
      "id": "Qwen3.5-27B|A100-40GBx4|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 0.1,
      "cost": 0,
      "domains": {
        "chat": 0.2,
        "coding": 0,
        "terminal": 0,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 447.3,
        "ttftMs": 14161.9,
        "tokPerSec": 87.6,
        "usdPerMTok": 25.23,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 50
      }
    },
    {
      "id": "Llama-3.1-70B|A100-40GBx4|sglang|BF16",
      "model": "Llama-3.1-70B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 0,
      "cost": 0,
      "domains": {
        "chat": 0,
        "coding": 0,
        "terminal": 0,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 149.7,
        "ttftMs": 32808.7,
        "tokPerSec": 94.7,
        "usdPerMTok": 23.35,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 35
      }
    },
    {
      "id": "Llama-3.3-70B|A100-40GBx4|sglang|BF16",
      "model": "Llama-3.3-70B",
      "hardware": "A100-40GBx4",
      "hardwareFamily": "A100",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 0,
      "cost": 0,
      "domains": {
        "chat": 0,
        "coding": 0,
        "terminal": 0,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 189.8,
        "ttftMs": 40884,
        "tokPerSec": 82.3,
        "usdPerMTok": 26.87,
        "loadsUsed": [
          1,
          40,
          160
        ],
        "domainCount": 4,
        "runCount": 30
      }
    },
    {
      "id": "Qwen3.5-27B|3090x4|sglang|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "sglang",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 0,
      "cost": 21.4,
      "domains": {
        "chat": 0,
        "coding": 0,
        "terminal": 0,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 441.7,
        "ttftMs": 13233,
        "tokPerSec": 56.6,
        "usdPerMTok": 4.32,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 39
      }
    },
    {
      "id": "Qwen3.5-27B|3090x4|vllm|BF16",
      "model": "Qwen3.5-27B",
      "hardware": "3090x4",
      "hardwareFamily": "3090",
      "gpus": 4,
      "engine": "vllm",
      "quant": "BF16",
      "provenance": "verified",
      "efficiency": 0,
      "cost": 34.2,
      "domains": {
        "chat": 0,
        "coding": 0,
        "terminal": 0,
        "computerUse": 0
      },
      "raw": {
        "tpotMs": 510.9,
        "ttftMs": 18074.8,
        "tokPerSec": 102,
        "usdPerMTok": 2.4,
        "loadsUsed": [
          1,
          40,
          120,
          160
        ],
        "domainCount": 4,
        "runCount": 41
      }
    }
  ]
} as EfficiencySnapshot;
