/**
 * Build the frozen Efficiency Index snapshot from a QuettaBench data JSON.
 *
 *   npx tsx scripts/build-efficiency-index.ts /tmp/qf-index/data.synthetic_distributional.json
 *   npx tsx scripts/build-efficiency-index.ts --check
 *
 * --check validates the committed snapshot without touching the network.
 * The site never fetches the corpus; it ships the snapshot as a literal.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  INDEX_VERSION,
  assertIndexInvariants,
  scoreCorpus,
  type BenchRun,
  type DomainScales,
  type IndexRow,
} from '../src/site/efficiency/score.ts';

const here = dirname(fileURLToPath(import.meta.url));
const snapshotPath = resolve(here, '../src/site/efficiency/snapshot.ts');

interface RawRow {
  hardware: string;
  modelShort: string;
  quant?: string;
  engineVersion?: string;
  config?: {
    backend?: string;
    profile?: string;
    concurrency?: number;
  };
  summary?: {
    successful_requests?: number;
    num_requests?: number;
    failed_requests?: number;
    median_tpot_ms?: number;
    median_ttft_ms?: number;
    output_token_throughput?: number;
  };
}

function toRuns(raw: RawRow[]): BenchRun[] {
  const runs: BenchRun[] = [];
  for (const r of raw) {
    const s = r.summary;
    const c = r.config;
    if (!s || !c || !c.profile || c.concurrency == null) continue;
    const n = s.num_requests ?? 0;
    const ok = s.successful_requests ?? (n - (s.failed_requests ?? 0));
    runs.push({
      hardware: r.hardware,
      modelShort: r.modelShort,
      quant: r.quant,
      engine: c.backend,
      profile: c.profile,
      concurrency: c.concurrency,
      successRate: n > 0 ? ok / n : 0,
      tpotMs: s.median_tpot_ms ?? NaN,
      ttftMs: s.median_ttft_ms ?? NaN,
      tokPerSec: s.output_token_throughput ?? NaN,
    });
  }
  return runs;
}

function emitSnapshot(rows: IndexRow[], scales: DomainScales, source: string, modified: string): string {
  const payload = {
    version: INDEX_VERSION,
    generatedAt: new Date().toISOString().slice(0, 10),
    source,
    sourceModified: modified,
    n: rows.length,
    verified: rows.filter((r) => r.provenance === 'verified').length,
    estimated: rows.filter((r) => r.provenance === 'estimated').length,
    scales,
    rows,
  };
  return `/* Generated by scripts/build-efficiency-index.ts — do not edit by hand. */\n` +
    `import type { DomainScales, IndexRow } from './score';\n\n` +
    `export interface EfficiencySnapshot {\n` +
    `  version: string;\n` +
    `  generatedAt: string;\n` +
    `  source: string;\n` +
    `  sourceModified: string;\n` +
    `  n: number;\n` +
    `  verified: number;\n` +
    `  estimated: number;\n` +
    `  scales: DomainScales;\n` +
    `  rows: IndexRow[];\n` +
    `}\n\n` +
    `export const EFFICIENCY_SNAPSHOT: EfficiencySnapshot = ${JSON.stringify(payload, null, 2)} as EfficiencySnapshot;\n`;
}

function checkCommitted(): void {
  const src = readFileSync(snapshotPath, 'utf8');
  const match = src.match(/export const EFFICIENCY_SNAPSHOT[\s\S]*? = ({[\s\S]*}) as EfficiencySnapshot;/);
  if (!match) {
    console.error('snapshot.ts: could not parse EFFICIENCY_SNAPSHOT');
    process.exit(1);
  }
  const snap = JSON.parse(match[1]) as { rows: IndexRow[] };
  const failures = assertIndexInvariants(snap.rows);
  if (failures.length) {
    console.error('snapshot check failed:');
    for (const f of failures) console.error(`  · ${f}`);
    process.exit(1);
  }
  console.log(`✓ efficiency snapshot: ${snap.rows.length} rows, invariants ok`);
}

function main(): void {
  const args = process.argv.slice(2);
  if (args.includes('--check')) {
    checkCommitted();
    return;
  }
  const input = args.find((a) => !a.startsWith('-'));
  if (!input) {
    console.error('usage: tsx scripts/build-efficiency-index.ts <data.json> | --check');
    process.exit(2);
  }
  const abs = resolve(input);
  const raw = JSON.parse(readFileSync(abs, 'utf8')) as RawRow[];
  const { rows, scales } = scoreCorpus(toRuns(raw), 'verified');
  const failures = assertIndexInvariants(rows);
  if (failures.length) {
    console.error('generated snapshot failed invariants:');
    for (const f of failures) console.error(`  · ${f}`);
    process.exit(1);
  }
  writeFileSync(
    snapshotPath,
    emitSnapshot(rows, scales, 'json/current/data.synthetic_distributional.json', '2026-08-30'),
  );
  const top = rows[0];
  const cheap = [...rows].filter((r) => r.cost != null).sort((a, b) => (b.cost ?? 0) - (a.cost ?? 0))[0];
  console.log(`wrote ${rows.length} rows → ${snapshotPath}`);
  console.log(`top efficiency  ${top.efficiency}  ${top.model} ${top.hardware} ${top.engine}`);
  if (cheap) console.log(`top cost        ${cheap.cost}  ${cheap.model} ${cheap.hardware} ${cheap.engine}`);
}

main();
