/**
 * Refresh the dated market references in src/site/efficiency/market.ts from
 * the public OpenRouter model list. Dev-only; the site bundle never fetches.
 *
 *   npm run refresh:market
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, '../src/site/efficiency/market.ts');

const SLUG = 'meta-llama/llama-3.1-8b-instruct';
const MODEL = 'Llama-3.1-8B';
const SOURCE = 'OpenRouter listed price, Meta Llama 3.1 8B Instruct';
const HREF = `https://openrouter.ai/${SLUG}`;

interface OpenRouterModel {
  id: string;
  pricing?: { prompt?: string; completion?: string };
}

function perMillion(perToken: string | undefined): number {
  const n = Number(perToken);
  if (!Number.isFinite(n) || n <= 0) throw new Error(`bad per-token price: ${perToken}`);
  // Round to the cent per million tokens.
  return Math.round(n * 1e6 * 100) / 100;
}

function render(usdIn: number, usdOut: number, asOf: string): string {
  return `/* Generated by scripts/refresh-market-refs.ts — edit the script, then \`npm run refresh:market\`. */

/**
 * Dated external price references. Shown beside the self-hosted TCO as a
 * sanity bound; never used to score any index.
 */
export const OPENROUTER_LLAMA31_8B = {
  model: '${MODEL}',
  slug: '${SLUG}',
  usdPerMTokIn: ${usdIn},
  usdPerMTokOut: ${usdOut},
  asOf: '${asOf}',
  scope: 'OpenRouter listed input/output price; the output price is what self-hosted output cost is compared with',
  source: '${SOURCE}',
  href: '${HREF}',
} as const;

/** How many times the self-hosted cost floor exceeds the API list price. */
export function selfHostedToApiRatio(selfHostedUsd: number, apiUsd: number): number | null {
  if (!(selfHostedUsd > 0) || !(apiUsd > 0)) return null;
  return selfHostedUsd / apiUsd;
}
`;
}

async function main(): Promise<void> {
  const res = await fetch('https://openrouter.ai/api/v1/models');
  if (!res.ok) throw new Error(`openrouter ${res.status}`);
  const body = (await res.json()) as { data: OpenRouterModel[] };
  const model = body.data.find((m) => m.id === SLUG);
  if (!model) throw new Error(`${SLUG} not listed`);
  const usdIn = perMillion(model.pricing?.prompt);
  const usdOut = perMillion(model.pricing?.completion);
  const asOf = new Date().toISOString().slice(0, 10);
  writeFileSync(target, render(usdIn, usdOut, asOf));
  console.log(`market.ts: ${SLUG} in $${usdIn}/M out $${usdOut}/M as of ${asOf}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
