/**
 * Refresh the dated market references in src/site/efficiency/market.ts from
 * the public OpenRouter model list. Dev-only; the site bundle never fetches.
 *
 *   npm run refresh:market
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, '../src/site/efficiency/market.ts');

const SLUG = 'meta-llama/llama-3.1-8b-instruct';
const MODEL = 'Llama-3.1-8B';
const SOURCE = 'OpenRouter listed price, Meta Llama 3.1 8B Instruct';
const HREF = `https://openrouter.ai/${SLUG}`;

interface OpenRouterEndpoint {
  provider_name: string;
  quantization?: string;
  pricing?: { prompt?: string; completion?: string };
}

function perMillion(perToken: string | undefined): number {
  const n = Number(perToken);
  if (!Number.isFinite(n) || n <= 0) throw new Error(`bad per-token price: ${perToken}`);
  // Round to the cent per million tokens.
  return Math.round(n * 1e6 * 100) / 100;
}

function median(xs: number[]): number {
  const sorted = [...xs].sort((a, b) => a - b);
  const middle = Math.floor(sorted.length / 2);
  return sorted.length % 2
    ? sorted[middle]
    : (sorted[middle - 1] + sorted[middle]) / 2;
}

function render(
  endpoints: Array<{
    provider: string;
    quantization: string;
    usdPerMTokIn: number;
    usdPerMTokOut: number;
  }>,
  asOf: string,
): string {
  const input = endpoints.map((endpoint) => endpoint.usdPerMTokIn);
  const output = endpoints.map((endpoint) => endpoint.usdPerMTokOut);
  const range = (xs: number[]) => ({
    min: Math.min(...xs),
    median: median(xs),
    max: Math.max(...xs),
  });
  return `/* Generated by scripts/refresh-market-refs.ts — edit the script, then \`npm run refresh:market\`. */

/**
 * Dated external price references. Shown beside the self-hosted TCO as a
 * sanity bound; never used to score any index.
 */
export const OPENROUTER_LLAMA31_8B = {
  model: '${MODEL}',
  slug: '${SLUG}',
  endpointCount: ${endpoints.length},
  usdPerMTokIn: ${JSON.stringify(range(input))},
  usdPerMTokOut: ${JSON.stringify(range(output))},
  endpoints: ${JSON.stringify(endpoints, null, 2)},
  asOf: '${asOf}',
  scope: 'OpenRouter endpoint input/output list-price range; the output median is used for the summary ratio',
  source: '${SOURCE}, endpoint list',
  href: '${HREF}',
} as const;

/** How many times the self-hosted cost floor exceeds the API list price. */
export function selfHostedToApiRatio(selfHostedUsd: number, apiUsd: number): number | null {
  if (!(selfHostedUsd > 0) || !(apiUsd > 0)) return null;
  return selfHostedUsd / apiUsd;
}
`;
}

async function main(): Promise<void> {
  const res = await fetch(`https://openrouter.ai/api/v1/models/${SLUG}/endpoints`);
  if (!res.ok) throw new Error(`openrouter ${res.status}`);
  const body = (await res.json()) as { data?: { endpoints?: OpenRouterEndpoint[] } };
  const endpoints = (body.data?.endpoints ?? []).map((endpoint) => ({
    provider: endpoint.provider_name,
    quantization: endpoint.quantization ?? 'unknown',
    usdPerMTokIn: perMillion(endpoint.pricing?.prompt),
    usdPerMTokOut: perMillion(endpoint.pricing?.completion),
  }));
  if (endpoints.length === 0) throw new Error(`${SLUG} has no listed endpoints`);
  const asOf = new Date().toISOString().slice(0, 10);
  writeFileSync(target, render(endpoints, asOf));
  console.log(`market.ts: ${SLUG}, ${endpoints.length} endpoints as of ${asOf}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
